#include "config.h"

#include "registry.h"

#include "internals.h"

test_description tests[] = {
  { test_1, "Tape with unknown block", 0 },
  { test_2, "TZX turbo data with zero pilot pulses and zero data", 0 },
  { test_3, "Writing empty .tap file", 0 },
  { test_4, "Invalid compressed file 1", 0 },
  { test_5, "Invalid compressed file 2", 0 },
  { test_6, "Pointer wraparound in SZX file", 0 },
  { test_7, "Invalid TZX GDB", 0 },
  { test_8, "Empty TZX DRB", 0 },
  { test_9, "Invalid TZX archive info block", 0 },
  { test_10, "Invalid hardware info block causes memory leak", 0 },
  { test_11, "Invalid Warajevo tape file", 0 },
  { test_12, "Invalid TZX custom info block causes memory leak", 0 },
  { test_13, "TZX loop end block with loop start block", 0 },
  { test_14, "TZX loop blocks", 0 },
  { test_15, "Complete TZX file", 0 },
  { test_16, "TZX loop blocks 2", 0 },
  { test_17, "TZX jump blocks", 0 },
  { test_18, "CSW empty file", 0 },
  { test_19, "Complete TZX to TAP conversion", 0 },
  { test_20, "SNA file with SP < 0x4000", 0 },
  { test_21, "SNA file with SP = 0xffff", 0 },
  { test_22, "MDR write protection 1", 0 },
  { test_23, "MDR write protection 2", 0 },
  { test_24, "Complete TZX timings", 0 },
  { test_25, "Writing SNA file", 0 },
  { test_26, "Writing +3 .Z80 file", 0 },
  { test_27, "Reading old SZX file", 0 },
  { test_28, "Zero tail length PZX file", 0 },
  { test_29, "No pilot pulse GDB TZX file", 0 },
  { test_30, "CSW conversion", 0 },
  { test_31, "Write SZX Z80R chunk", 0 },
  { test_32, "Write SZX SPCR chunk", 0 },
  { test_33, "Write SZX JOY chunk", 0 },
  { test_34, "Write SZX KEYB chunk", 0 },
  { test_35, "Write SZX ZXPR chunk", 0 },
  { test_36, "Write SZX AY chunk", 0 },
  { test_37, "Write SZX SCLD chunk", 0 },
  { test_38, "Write SZX ZXAT chunk", 0 },
  { test_39, "Write SZX ZXCF chunk", 0 },
  { test_40, "Write SZX AMXM chunk", 0 },
  { test_41, "Write SZX SIDE chunk", 0 },
  { test_42, "Write SZX DRUM chunk", 0 },
  { test_43, "Write SZX COVX chunk", 0 },
  { test_44, "Read SZX Z80R chunk", 0 },
  { test_45, "Read SZX SPCR chunk", 0 },
  { test_46, "Read SZX JOY chunk", 0 },
  { test_47, "Read SZX KEYB chunk", 0 },
  { test_48, "Read SZX ZXPR chunk", 0 },
  { test_49, "Read SZX AY chunk", 0 },
  { test_50, "Read SZX SCLD chunk", 0 },
  { test_51, "Read SZX ZXAT chunk", 0 },
  { test_52, "Read SZX ZXCF chunk", 0 },
  { test_53, "Read SZX AMXM chunk", 0 },
  { test_54, "Read SZX SIDE chunk", 0 },
  { test_55, "Read SZX DRUM chunk", 0 },
  { test_56, "Read SZX COVX chunk", 0 },
  { test_57, "Write SZX ZMMC chunk", 0 },
  { test_58, "Read SZX ZMMC chunk", 0 },
  { test_59, "Write SZX RAMP chunk", 0 },
  { test_60, "Read SZX RAMP chunk", 0 },
  { test_61, "Write SZX ATRP chunk", 0 },
  { test_62, "Write SZX CFRP chunk", 0 },
  { test_63, "Read SZX ATRP chunk", 0 },
  { test_64, "Read SZX CFRP chunk", 0 },
  { test_65, "Write uncompressed SZX RAMP chunk", 0 },
  { test_66, "Write uncompressed SZX ATRP chunk", 0 },
  { test_67, "Write uncompressed SZX CFRP chunk", 0 },
  { test_68, "Read uncompressed SZX RAMP chunk", 0 },
  { test_69, "Read uncompressed SZX ATRP chunk", 0 },
  { test_70, "Read uncompressed SZX CFRP chunk", 0 },
  { test_71, "Write RZX with incompressible snap", 0 },
  { test_72, "Tape peek next block", 0 },
  { test_73, "Read TZX RAW block edge handling", 0 },
  { test_74, "Trailing pause block TZX file", 0 },
  { test_75, "Read mono WAV threshold fixture", 0 },
  { test_76, "Read stereo WAV mixdown fixture", 0 },
  { test_77, "Buffer write_byte stores single byte", 0 },
  { test_78, "Buffer write_word stores little-endian word", 0 },
  { test_79, "Buffer write_dword stores little-endian dword", 0 },
  { test_80, "Buffer write_buffer copies src contents to dest", 0 },
  { test_81, "Buffer is_empty and is_not_empty", 0 },
  { test_82, "Buffer clear resets data size to zero", 0 },
  { test_83, "Buffer set fills N bytes with given value", 0 },
  { test_84, "Buffer append copies src to raw byte buffer", 0 },
  { test_85, "Creator alloc/free and program getter/setter", 0 },
  { test_86, "Creator major and minor version getter/setter", 0 },
  { test_87, "Creator competition_code and custom data getter/setter", 0 },
  { test_88, "Snap main Z80 register getter/setter (a, f, bc, de, hl, alternates)", 0 },
  { test_89, "Snap index and special register getter/setter (ix, iy, i, r, sp, pc)", 0 },
  { test_90, "Snap Z80 status getter/setter (iff1, iff2, im, tstates, halted)", 0 },
  { test_91, "Microdrive alloc/free and write_protect getter/setter", 0 },
  { test_92, "Microdrive cartridge_len and data getter/setter", 0 },
  { test_93, "Microdrive mdr_write/mdr_read roundtrip", 0 },
  { test_94, "Snap machine type getter/setter and default value", 0 },
  { test_95, "Snap memptr getter/setter", 0 },
  { test_96, "Snap ULA, 128K memory port, and AY register port getter/setter", 0 },
  { test_97, "Snap custom_rom flag and custom_rom_pages getter/setter", 0 },
  { test_98, "Snap RAM pages getter/setter", 0 },
  { test_99, "Snap interface1 active, paged, and drive_count getter/setter", 0 },
  { test_100, "Snap DivIDE active, eprom_writeprotect, paged, and control getter/setter", 0 },
  { test_101, "Snap SpecDrum active flag and signed DAC getter/setter", 0 },
  { test_102, "Snap Fuller Box active flag getter/setter", 0 },
  { test_103, "Snap Multiface active, paged, model, disabled, and software_lockout getter/setter", 0 },
  { test_104, "Snap AY registers array getter/setter (all 16 registers)", 0 },
  { test_105, "Snap beta disk active, paged, autoboot, and drive_count getter/setter", 0 },
  { test_106, "Snap ZXATASP active, upload, and writeprotect getter/setter", 0 },
  { test_107, "Snap ZXATASP port_a/b/c and control getter/setter", 0 },
  { test_108, "Snap ZXATASP pages and current_page getter/setter", 0 },
  { test_109, "PZX archive info tags (title and Author) correctly parsed", 0 },
  { test_110, "Snap DivIDE pages count and divide_eprom pointer getter/setter", 0 },
  { test_111, "Snap DivIDE RAM page pointer array getter/setter", 0 },
  { test_112, "Snap DivMMC active, eprom_writeprotect, paged, and control getter/setter", 0 },
  { test_113, "Snap DivMMC pages count and divmmc_eprom pointer getter/setter", 0 },
  { test_114, "Snap Plus D active, paged, drive_count, custom_rom, and direction getter/setter", 0 },
  { test_115, "Snap Plus D FDC byte registers (control, track, sector, data, status) getter/setter", 0 },
  { test_116, "Snap Plus D ROM and RAM single-pointer getter/setter", 0 },
  { test_117, "Snap ZXATASP RAM page pointer array getter/setter", 0 },
  { test_118, "Snap Opus Discovery active, paged, drive_count, custom_rom, and direction getter/setter", 0 },
  { test_119, "Snap Opus Discovery FDC byte registers (track, sector, data, status, VIA ports) getter/setter", 0 },
  { test_120, "Snap Opus Discovery ROM and RAM single-pointer getter/setter", 0 },
  { test_121, "Snap Spectranet boolean int flags getter/setter", 0 },
  { test_122, "Snap Spectranet page_a/b, programmable_trap word, and memory pointers getter/setter", 0 },
  { test_123, "Snap DISCiPLE active, paged, inhibit_button, drive_count, custom_rom, and direction getter/setter", 0 },
  { test_124, "Snap DISCiPLE FDC byte registers (control, track, sector, data, status) getter/setter", 0 },
  { test_125, "Snap DISCiPLE ROM pointer, ROM length, and RAM pointer getter/setter", 0 },
  { test_126, "Snap USource active, paged, custom_rom int flags getter/setter", 0 },
  { test_127, "Snap USource ROM pointer and ROM length getter/setter", 0 },
  { test_128, "Snap USpeeched active and paged getter/setter", 0 },
  { test_129, "Snap Didaktik80 int flags and FDC byte registers getter/setter", 0 },
  { test_130, "Snap Didaktik80 ROM pointer, ROM length, and RAM pointer getter/setter", 0 },
  { test_131, "Snap ULAplus active, palette_enabled, current_register, palette, and ff_register getter/setter", 0 },
  { test_132, "Snap late_timings getter/setter", 0 },
  { test_133, "Snap zx_printer_active getter/setter", 0 },
  { test_134, "Snap covox_active and covox_dac getter/setter", 0 },
  { test_135, "Snap multiface_red_button_disabled getter/setter", 0 },
  { test_136, "Snap multiface_ram pointer and multiface_ram_length getter/setter", 0 },
  { test_137, "Snap zxmmc_active getter/setter", 0 },
  { test_138, "Snap ttx2000s_active getter/setter", 0 },
  { test_139, "Tape TURBO block pilot_length, sync1_length, sync2_length getter/setter", 0 },
  { test_140, "Tape TURBO block bit0_length, bit1_length, pilot_pulses, pause getter/setter", 0 },
  { test_141, "Tape PURE_TONE block pulse_length and count getter/setter", 0 },
  { test_142, "Tape PURE_DATA block bit0_length, bit1_length, bits_in_last_byte, pause getter/setter", 0 },
  { test_143, "Tape PAUSE block pause length and level getter/setter", 0 }
};

size_t test_count = ARRAY_SIZE( tests );
