#include "config.h"

#include "registry.h"

#include "internals.h"

#define TEST_ENTRY( x, description ) { x, #x, description, 0 }

test_description tests[] = {
  TEST_ENTRY( tape_with_unknown_block, "Tape with unknown block" ),
  TEST_ENTRY( tzx_turbo_data_with_zero_pilot_pulses_and_zero_data,
              "TZX turbo data with zero pilot pulses and zero data" ),
  TEST_ENTRY( writing_empty_tap_file, "Writing empty .tap file" ),
  TEST_ENTRY( invalid_compressed_file_1, "Invalid compressed file 1" ),
  TEST_ENTRY( invalid_compressed_file_2, "Invalid compressed file 2" ),
  TEST_ENTRY( pointer_wraparound_in_szx_file,
              "Pointer wraparound in SZX file" ),
  TEST_ENTRY( invalid_tzx_gdb, "Invalid TZX GDB" ),
  TEST_ENTRY( empty_tzx_drb, "Empty TZX DRB" ),
  TEST_ENTRY( invalid_tzx_archive_info_block,
              "Invalid TZX archive info block" ),
  TEST_ENTRY( invalid_hardware_info_block_causes_memory_leak,
              "Invalid hardware info block causes memory leak" ),
  TEST_ENTRY( invalid_warajevo_tape_file, "Invalid Warajevo tape file" ),
  TEST_ENTRY( invalid_tzx_custom_info_block_causes_memory_leak,
              "Invalid TZX custom info block causes memory leak" ),
  TEST_ENTRY( tzx_loop_end_block_with_loop_start_block,
              "TZX loop end block with loop start block" ),
  TEST_ENTRY( tzx_loop_blocks, "TZX loop blocks" ),
  TEST_ENTRY( complete_tzx_file, "Complete TZX file" ),
  TEST_ENTRY( tzx_loop_blocks_2, "TZX loop blocks 2" ),
  TEST_ENTRY( tzx_jump_blocks, "TZX jump blocks" ),
  TEST_ENTRY( csw_empty_file, "CSW empty file" ),
  TEST_ENTRY( complete_tzx_to_tap_conversion,
              "Complete TZX to TAP conversion" ),
  TEST_ENTRY( sna_file_with_sp_0x4000, "SNA file with SP < 0x4000" ),
  TEST_ENTRY( sna_file_with_sp_0xffff, "SNA file with SP = 0xffff" ),
  TEST_ENTRY( mdr_write_protection_1, "MDR write protection 1" ),
  TEST_ENTRY( mdr_write_protection_2, "MDR write protection 2" ),
  TEST_ENTRY( complete_tzx_timings, "Complete TZX timings" ),
  TEST_ENTRY( writing_sna_file, "Writing SNA file" ),
  TEST_ENTRY( writing_plus_3_z80_file, "Writing +3 .Z80 file" ),
  TEST_ENTRY( reading_old_szx_file, "Reading old SZX file" ),
  TEST_ENTRY( rzx_invalid_frame_data_error_does_not_free_repeat_frame_pointer,
              "RZX frame data error does not free repeat-frame pointer" ),
  TEST_ENTRY( zero_tail_length_pzx_file, "Zero tail length PZX file" ),
  TEST_ENTRY( no_pilot_pulse_gdb_tzx_file, "No pilot pulse GDB TZX file" ),
  TEST_ENTRY( csw_conversion, "CSW conversion" ),
  TEST_ENTRY( write_szx_z80r_chunk, "Write SZX Z80R chunk" ),
  TEST_ENTRY( write_szx_spcr_chunk, "Write SZX SPCR chunk" ),
  TEST_ENTRY( write_szx_joy_chunk, "Write SZX JOY chunk" ),
  TEST_ENTRY( write_szx_keyb_chunk, "Write SZX KEYB chunk" ),
  TEST_ENTRY( write_szx_zxpr_chunk, "Write SZX ZXPR chunk" ),
  TEST_ENTRY( write_szx_ay_chunk, "Write SZX AY chunk" ),
  TEST_ENTRY( write_szx_scld_chunk, "Write SZX SCLD chunk" ),
  TEST_ENTRY( write_szx_zxat_chunk, "Write SZX ZXAT chunk" ),
  TEST_ENTRY( write_szx_zxcf_chunk, "Write SZX ZXCF chunk" ),
  TEST_ENTRY( write_szx_amxm_chunk, "Write SZX AMXM chunk" ),
  TEST_ENTRY( write_szx_side_chunk, "Write SZX SIDE chunk" ),
  TEST_ENTRY( write_szx_drum_chunk, "Write SZX DRUM chunk" ),
  TEST_ENTRY( write_szx_covx_chunk, "Write SZX COVX chunk" ),
  TEST_ENTRY( read_szx_z80r_chunk, "Read SZX Z80R chunk" ),
  TEST_ENTRY( read_szx_spcr_chunk, "Read SZX SPCR chunk" ),
  TEST_ENTRY( read_szx_joy_chunk, "Read SZX JOY chunk" ),
  TEST_ENTRY( read_szx_keyb_chunk, "Read SZX KEYB chunk" ),
  TEST_ENTRY( read_szx_zxpr_chunk, "Read SZX ZXPR chunk" ),
  TEST_ENTRY( read_szx_ay_chunk, "Read SZX AY chunk" ),
  TEST_ENTRY( read_szx_scld_chunk, "Read SZX SCLD chunk" ),
  TEST_ENTRY( read_szx_zxat_chunk, "Read SZX ZXAT chunk" ),
  TEST_ENTRY( read_szx_zxcf_chunk, "Read SZX ZXCF chunk" ),
  TEST_ENTRY( read_szx_amxm_chunk, "Read SZX AMXM chunk" ),
  TEST_ENTRY( read_szx_side_chunk, "Read SZX SIDE chunk" ),
  TEST_ENTRY( read_szx_drum_chunk, "Read SZX DRUM chunk" ),
  TEST_ENTRY( read_szx_covx_chunk, "Read SZX COVX chunk" ),
  TEST_ENTRY( write_szx_zmmc_chunk, "Write SZX ZMMC chunk" ),
  TEST_ENTRY( read_szx_zmmc_chunk, "Read SZX ZMMC chunk" ),
  TEST_ENTRY( write_szx_ramp_chunk, "Write SZX RAMP chunk" ),
  TEST_ENTRY( read_szx_ramp_chunk, "Read SZX RAMP chunk" ),
  TEST_ENTRY( write_szx_atrp_chunk, "Write SZX ATRP chunk" ),
  TEST_ENTRY( write_szx_cfrp_chunk, "Write SZX CFRP chunk" ),
  TEST_ENTRY( read_szx_atrp_chunk, "Read SZX ATRP chunk" ),
  TEST_ENTRY( read_szx_cfrp_chunk, "Read SZX CFRP chunk" ),
  TEST_ENTRY( write_uncompressed_szx_ramp_chunk, "Write uncompressed SZX RAMP chunk" ),
  TEST_ENTRY( write_uncompressed_szx_atrp_chunk, "Write uncompressed SZX ATRP chunk" ),
  TEST_ENTRY( write_uncompressed_szx_cfrp_chunk, "Write uncompressed SZX CFRP chunk" ),
  TEST_ENTRY( read_uncompressed_szx_ramp_chunk, "Read uncompressed SZX RAMP chunk" ),
  TEST_ENTRY( read_uncompressed_szx_atrp_chunk, "Read uncompressed SZX ATRP chunk" ),
  TEST_ENTRY( read_uncompressed_szx_cfrp_chunk, "Read uncompressed SZX CFRP chunk" ),
  TEST_ENTRY( write_rzx_with_incompressible_snap, "Write RZX with incompressible snap" ),
  TEST_ENTRY( tape_peek_next_block, "Tape peek next block" ),
  TEST_ENTRY( read_tzx_raw_block_edge_handling, "Read TZX RAW block edge handling" ),
  TEST_ENTRY( trailing_pause_block_tzx_file, "Trailing pause block TZX file" ),
  TEST_ENTRY( read_mono_wav_threshold_fixture, "Read mono WAV threshold fixture" ),
  TEST_ENTRY( read_stereo_wav_mixdown_fixture, "Read stereo WAV mixdown fixture" ),
  TEST_ENTRY( buffer_write_byte_stores_single_byte, "Buffer write_byte stores single byte" ),
  TEST_ENTRY( buffer_write_word_stores_little_endian_word, "Buffer write_word stores little-endian word" ),
  TEST_ENTRY( buffer_write_dword_stores_little_endian_dword, "Buffer write_dword stores little-endian dword" ),
  TEST_ENTRY( buffer_write_buffer_copies_src_contents_to_dest, "Buffer write_buffer copies src contents to dest" ),
  TEST_ENTRY( buffer_empty_predicates, "Buffer is_empty and is_not_empty" ),
  TEST_ENTRY( buffer_clear_resets_data_size_to_zero, "Buffer clear resets data size to zero" ),
  TEST_ENTRY( buffer_set_fills_n_bytes_with_given_value, "Buffer set fills N bytes with given value" ),
  TEST_ENTRY( buffer_append_copies_src_to_raw_byte_buffer, "Buffer append copies src to raw byte buffer" ),
  TEST_ENTRY( creator_alloc_free_and_program_getter_setter, "Creator alloc/free and program getter/setter" ),
  TEST_ENTRY( creator_major_and_minor_version_getter_setter, "Creator major and minor version getter/setter" ),
  TEST_ENTRY( creator_competition_code_and_custom_data_getter_setter, "Creator competition_code and custom data getter/setter" ),
  TEST_ENTRY( snap_main_z80_register_getter_setter_a_f_bc_de_hl_alternates, "Snap main Z80 register getter/setter (a, f, bc, de, hl, alternates)" ),
  TEST_ENTRY( snap_index_and_special_register_getter_setter_ix_iy_i_r_sp_pc, "Snap index and special register getter/setter (ix, iy, i, r, sp, pc)" ),
  TEST_ENTRY( snap_z80_status_getter_setter_iff1_iff2_im_tstates_halted, "Snap Z80 status getter/setter (iff1, iff2, im, tstates, halted)" ),
  TEST_ENTRY( microdrive_alloc_free_and_write_protect_getter_setter, "Microdrive alloc/free and write_protect getter/setter" ),
  TEST_ENTRY( microdrive_cartridge_len_and_data_getter_setter, "Microdrive cartridge_len and data getter/setter" ),
  TEST_ENTRY( microdrive_mdr_write_mdr_read_roundtrip, "Microdrive mdr_write/mdr_read roundtrip" ),
  TEST_ENTRY( snap_machine_type_getter_setter_and_default_value, "Snap machine type getter/setter and default value" ),
  TEST_ENTRY( snap_memptr_getter_setter, "Snap memptr getter/setter" ),
  TEST_ENTRY( snap_ula_128k_memory_port_and_ay_register_port_getter_setter, "Snap ULA, 128K memory port, and AY register port getter/setter" ),
  TEST_ENTRY( snap_custom_rom_flag_and_custom_rom_pages_getter_setter, "Snap custom_rom flag and custom_rom_pages getter/setter" ),
  TEST_ENTRY( snap_ram_pages_getter_setter, "Snap RAM pages getter/setter" ),
  TEST_ENTRY( snap_interface1_active_paged_and_drive_count_getter_setter, "Snap interface1 active, paged, and drive_count getter/setter" ),
  TEST_ENTRY( snap_divide_active_eprom_writeprotect_paged_and_control_getter_setter, "Snap DivIDE active, eprom_writeprotect, paged, and control getter/setter" ),
  TEST_ENTRY( snap_specdrum_active_flag_and_signed_dac_getter_setter, "Snap SpecDrum active flag and signed DAC getter/setter" ),
  TEST_ENTRY( snap_fuller_box_active_flag_getter_setter, "Snap Fuller Box active flag getter/setter" ),
  TEST_ENTRY( snap_multiface_active_paged_model_disabled_and_software_lockout_getter_setter, "Snap Multiface active, paged, model, disabled, and software_lockout getter/setter" ),
  TEST_ENTRY( snap_ay_registers_array_getter_setter_all_16_registers, "Snap AY registers array getter/setter (all 16 registers)" ),
  TEST_ENTRY( snap_beta_disk_active_paged_autoboot_and_drive_count_getter_setter, "Snap beta disk active, paged, autoboot, and drive_count getter/setter" ),
  TEST_ENTRY( snap_zxatasp_active_upload_and_writeprotect_getter_setter, "Snap ZXATASP active, upload, and writeprotect getter/setter" ),
  TEST_ENTRY( snap_zxatasp_port_a_b_c_and_control_getter_setter, "Snap ZXATASP port_a/b/c and control getter/setter" ),
  TEST_ENTRY( snap_zxatasp_pages_and_current_page_getter_setter, "Snap ZXATASP pages and current_page getter/setter" ),
  TEST_ENTRY( pzx_archive_info_tags_title_and_author_correctly_parsed, "PZX archive info tags (title and Author) correctly parsed" ),
  TEST_ENTRY( snap_divide_pages_count_and_divide_eprom_pointer_getter_setter, "Snap DivIDE pages count and divide_eprom pointer getter/setter" ),
  TEST_ENTRY( snap_divide_ram_page_pointer_array_getter_setter, "Snap DivIDE RAM page pointer array getter/setter" ),
  TEST_ENTRY( snap_divmmc_active_eprom_writeprotect_paged_and_control_getter_setter, "Snap DivMMC active, eprom_writeprotect, paged, and control getter/setter" ),
  TEST_ENTRY( snap_divmmc_pages_count_and_divmmc_eprom_pointer_getter_setter, "Snap DivMMC pages count and divmmc_eprom pointer getter/setter" ),
  TEST_ENTRY( snap_plus_d_active_paged_drive_count_custom_rom_and_direction_getter_setter, "Snap Plus D active, paged, drive_count, custom_rom, and direction getter/setter" ),
  TEST_ENTRY( snap_plus_d_fdc_byte_registers_control_track_sector_data_status_getter_setter, "Snap Plus D FDC byte registers (control, track, sector, data, status) getter/setter" ),
  TEST_ENTRY( snap_plus_d_rom_and_ram_single_pointer_getter_setter, "Snap Plus D ROM and RAM single-pointer getter/setter" ),
  TEST_ENTRY( snap_zxatasp_ram_page_pointer_array_getter_setter, "Snap ZXATASP RAM page pointer array getter/setter" ),
  TEST_ENTRY( snap_opus_discovery_active_paged_drive_count_custom_rom_and_direction_getter_setter, "Snap Opus Discovery active, paged, drive_count, custom_rom, and direction getter/setter" ),
  TEST_ENTRY( snap_opus_discovery_fdc_byte_registers_track_sector_data_status_via_ports_getter_setter, "Snap Opus Discovery FDC byte registers (track, sector, data, status, VIA ports) getter/setter" ),
  TEST_ENTRY( snap_opus_discovery_rom_and_ram_single_pointer_getter_setter, "Snap Opus Discovery ROM and RAM single-pointer getter/setter" ),
  TEST_ENTRY( snap_spectranet_boolean_int_flags_getter_setter, "Snap Spectranet boolean int flags getter/setter" ),
  TEST_ENTRY( snap_spectranet_page_a_b_programmable_trap_word_and_memory_pointers_getter_setter, "Snap Spectranet page_a/b, programmable_trap word, and memory pointers getter/setter" ),
  TEST_ENTRY( snap_disciple_active_paged_inhibit_button_drive_count_custom_rom_and_direction_getter_setter, "Snap DISCiPLE active, paged, inhibit_button, drive_count, custom_rom, and direction getter/setter" ),
  TEST_ENTRY( snap_disciple_fdc_byte_registers_control_track_sector_data_status_getter_setter, "Snap DISCiPLE FDC byte registers (control, track, sector, data, status) getter/setter" ),
  TEST_ENTRY( snap_disciple_rom_pointer_rom_length_and_ram_pointer_getter_setter, "Snap DISCiPLE ROM pointer, ROM length, and RAM pointer getter/setter" ),
  TEST_ENTRY( snap_usource_active_paged_custom_rom_int_flags_getter_setter, "Snap USource active, paged, custom_rom int flags getter/setter" ),
  TEST_ENTRY( snap_usource_rom_pointer_and_rom_length_getter_setter, "Snap USource ROM pointer and ROM length getter/setter" ),
  TEST_ENTRY( snap_uspeeched_active_and_paged_getter_setter, "Snap USpeeched active and paged getter/setter" ),
  TEST_ENTRY( snap_didaktik80_int_flags_and_fdc_byte_registers_getter_setter, "Snap Didaktik80 int flags and FDC byte registers getter/setter" ),
  TEST_ENTRY( snap_didaktik80_rom_pointer_rom_length_and_ram_pointer_getter_setter, "Snap Didaktik80 ROM pointer, ROM length, and RAM pointer getter/setter" ),
  TEST_ENTRY( snap_ulaplus_active_palette_enabled_current_register_palette_and_ff_register_getter_setter, "Snap ULAplus active, palette_enabled, current_register, palette, and ff_register getter/setter" ),
  TEST_ENTRY( snap_late_timings_getter_setter, "Snap late_timings getter/setter" ),
  TEST_ENTRY( snap_zx_printer_active_getter_setter, "Snap zx_printer_active getter/setter" ),
  TEST_ENTRY( snap_covox_active_and_covox_dac_getter_setter, "Snap covox_active and covox_dac getter/setter" ),
  TEST_ENTRY( snap_multiface_red_button_disabled_getter_setter, "Snap multiface_red_button_disabled getter/setter" ),
  TEST_ENTRY( snap_multiface_ram_pointer_and_multiface_ram_length_getter_setter, "Snap multiface_ram pointer and multiface_ram_length getter/setter" ),
  TEST_ENTRY( snap_zxmmc_active_getter_setter, "Snap zxmmc_active getter/setter" ),
  TEST_ENTRY( snap_ttx2000s_active_getter_setter, "Snap ttx2000s_active getter/setter" ),
  TEST_ENTRY( tape_turbo_block_pilot_length_sync1_length_sync2_length_getter_setter, "Tape TURBO block pilot_length, sync1_length, sync2_length getter/setter" ),
  TEST_ENTRY( tape_turbo_block_bit0_length_bit1_length_pilot_pulses_pause_getter_setter, "Tape TURBO block bit0_length, bit1_length, pilot_pulses, pause getter/setter" ),
  TEST_ENTRY( tape_pure_tone_block_pulse_length_and_count_getter_setter, "Tape PURE_TONE block pulse_length and count getter/setter" ),
  TEST_ENTRY( tape_pure_data_block_bit0_length_bit1_length_bits_in_last_byte_pause_getter_setter, "Tape PURE_DATA block bit0_length, bit1_length, bits_in_last_byte, pause getter/setter" ),
  TEST_ENTRY( tape_pause_block_pause_length_and_level_getter_setter, "Tape PAUSE block pause length and level getter/setter" ),
  TEST_ENTRY( tape_pulses_block_count_and_pulse_lengths_getter_setter, "Tape PULSES block count and pulse_lengths getter/setter" ),
  TEST_ENTRY( tape_pulse_sequence_block_count_pulse_lengths_and_pulse_repeats_getter_setter, "Tape PULSE_SEQUENCE block count, pulse_lengths, and pulse_repeats getter/setter" ),
  TEST_ENTRY( tape_raw_data_block_bit_length_bits_in_last_byte_data_data_length_and_pause_getter_setter, "Tape RAW_DATA block bit_length, bits_in_last_byte, data, data_length, and pause getter/setter" ),
  TEST_ENTRY( tape_data_block_count_tail_length_level_data_and_bit_pulses_getter_setter, "Tape DATA_BLOCK count, tail_length, level, data, and bit0/bit1 pulses getter/setter" ),
  TEST_ENTRY( tape_group_start_block_text_getter_setter, "Tape GROUP_START block text getter/setter" ),
  TEST_ENTRY( tape_loop_start_block_count_getter_setter, "Tape LOOP_START block count getter/setter" ),
  TEST_ENTRY( tape_set_signal_level_block_level_getter_setter, "Tape SET_SIGNAL_LEVEL block level getter/setter" ),
  TEST_ENTRY( rzx_alloc_and_free_lifecycle, "RZX alloc and free lifecycle" ),
  TEST_ENTRY( rzx_start_input_stop_input_and_tstates_accessor, "RZX start_input, stop_input, and tstates accessor" ),
  TEST_ENTRY( rzx_store_frame_and_iterator_get_frames_count, "RZX store_frame and iterator_get_frames count" ),
  TEST_ENTRY( rzx_store_frame_repeat_frame_detection, "RZX store_frame repeat frame detection" ),
  TEST_ENTRY( rzx_add_snap_inserts_snapshot_block, "RZX add_snap inserts snapshot block" ),
  TEST_ENTRY( rzx_iterator_begin_next_last_with_snap_and_input_blocks, "RZX iterator begin/next/last with snap and input blocks" ),
  TEST_ENTRY( rzx_get_keyid_returns_zero_with_no_signature_block, "RZX get_keyid returns zero with no signature block" ),
  TEST_ENTRY( rzx_iterator_get_frames_returns_size_t_max_for_non_input_block, "RZX iterator_get_frames returns SIZE_MAX for non-input block" ),
  TEST_ENTRY( snap_kempston_mouse_active_getter_setter, "Snap kempston_mouse_active getter/setter" ),
  TEST_ENTRY( snap_interface1_custom_rom_rom_pointer_and_rom_length_getter_setter, "Snap interface1 custom_rom flag, ROM pointer, and ROM length getter/setter" ),
  TEST_ENTRY( tape_rom_block_data_data_length_and_pause_getter_setter, "Tape ROM block data, data_length, and pause getter/setter" ),
  TEST_ENTRY( tzx_pulse_sequence_over_255_splits_into_multiple_pulses_blocks, "TZX PULSE_SEQUENCE over 255 pulses splits into multiple PULSES blocks" ),
};

size_t test_count = ARRAY_SIZE( tests );
